/**
 * Curated emoji for the in-app picker — iOS can't open the system emoji
 * keyboard from a web app, so the picker ships its own set plus search.
 * Each entry is [character, search keywords]; the character must be a single
 * grapheme and the keywords drive the search box (both enforced by tests).
 */
export type EmojiEntry = readonly [char: string, keywords: string]

export const EMOJI_CATEGORIES: { label: string; emoji: EmojiEntry[] }[] = [
  {
    label: 'smileys',
    emoji: [
      ['😀', 'grinning grin happy smile face'],
      ['😃', 'smiley happy grin joy face'],
      ['😄', 'smile happy grin laugh face'],
      ['😁', 'beaming grin happy teeth'],
      ['😆', 'laughing satisfied haha squint'],
      ['😅', 'sweat smile nervous laugh relief'],
      ['😂', 'joy tears laugh crying funny lol'],
      ['🤣', 'rofl rolling floor laughing funny'],
      ['🙂', 'slight smile happy'],
      ['😉', 'wink flirt joke'],
      ['😊', 'blush smile happy warm'],
      ['😇', 'innocent angel halo good'],
      ['🥰', 'smiling hearts love adore'],
      ['😍', 'heart eyes love crush'],
      ['🤩', 'star struck excited wow amazed'],
      ['😘', 'kiss blowing love'],
      ['😋', 'yum delicious tasty savoring tongue'],
      ['😛', 'tongue out playful silly'],
      ['😜', 'winking tongue playful zany'],
      ['🤪', 'zany goofy crazy wild silly'],
      ['🤨', 'raised eyebrow skeptical suspicious'],
      ['🧐', 'monocle inspect curious scrutiny'],
      ['🤓', 'nerd geek glasses smart study'],
      ['😎', 'sunglasses cool confident'],
      ['🥳', 'partying party celebrate birthday'],
      ['😏', 'smirk sly smug'],
      ['😌', 'relieved calm content peaceful'],
      ['😔', 'pensive sad down disappointed'],
      ['😴', 'sleeping sleep zzz tired bed rest'],
      ['🥱', 'yawning tired bored sleepy'],
      ['😷', 'mask sick medical face'],
      ['🤒', 'thermometer sick fever ill'],
      ['🤢', 'nauseated sick gross queasy'],
      ['🥶', 'cold freezing frozen ice'],
      ['🥵', 'hot heat sweating overheated'],
      ['😳', 'flushed embarrassed shocked'],
      ['🥺', 'pleading puppy eyes begging'],
      ['😢', 'cry sad tear'],
      ['😭', 'sobbing crying loudly bawl sad'],
      ['😤', 'triumph steam frustrated determined'],
      ['😠', 'angry mad annoyed'],
      ['🤯', 'mind blown exploding head shock'],
      ['😱', 'scream fear scared shock'],
      ['🤗', 'hug hugging warm'],
      ['🤫', 'shush quiet secret silence'],
      ['🤔', 'thinking think hmm ponder consider'],
      ['🙄', 'eye roll annoyed whatever'],
      ['😬', 'grimace awkward cringe nervous'],
    ],
  },
  {
    label: 'people',
    emoji: [
      ['👍', 'thumbs up like yes approve good'],
      ['👎', 'thumbs down dislike no bad'],
      ['👌', 'ok perfect fine hand'],
      ['✌️', 'victory peace fingers hand'],
      ['🤞', 'crossed fingers luck hope'],
      ['🤟', 'love you gesture hand'],
      ['🤘', 'rock horns metal hand'],
      ['🤙', 'call me shaka hang loose'],
      ['👈', 'point left hand finger'],
      ['👉', 'point right hand finger'],
      ['👆', 'point up hand finger'],
      ['👇', 'point down hand finger'],
      ['✋', 'raised hand stop palm high five'],
      ['👋', 'wave hello goodbye hi bye hand'],
      ['🤝', 'handshake deal agreement meeting'],
      ['👏', 'clap applause praise'],
      ['🙌', 'raising hands celebration hooray praise'],
      ['🙏', 'pray thanks please namaste gratitude'],
      ['✍️', 'writing hand write note journal pen'],
      ['💪', 'muscle flex strong gym workout biceps lift'],
      ['🧠', 'brain mind smart think study learn'],
      ['👀', 'eyes look watch see'],
      ['👂', 'ear listen hear'],
      ['👃', 'nose smell'],
      ['🦷', 'tooth teeth dentist brush floss'],
      ['👶', 'baby infant child'],
      ['🧒', 'child kid young'],
      ['🧑', 'person adult human'],
      ['👨', 'man male person'],
      ['👩', 'woman female person'],
      ['🧓', 'older person elder grandparent'],
      ['🚶', 'walking walk steps pedestrian stroll'],
      ['🏃', 'running run jog exercise cardio workout race'],
      ['🧎', 'kneeling kneel'],
      ['💃', 'dancing dance woman party'],
      ['🕺', 'dancing man dance party'],
      ['🤳', 'selfie phone photo camera'],
      ['🛀', 'bath bathing bathtub relax soak'],
    ],
  },
  {
    label: 'activity',
    emoji: [
      ['⚽', 'soccer football ball sport'],
      ['🏀', 'basketball ball hoops sport'],
      ['🏈', 'american football ball sport'],
      ['⚾', 'baseball ball sport'],
      ['🎾', 'tennis ball racket sport'],
      ['🏐', 'volleyball ball sport'],
      ['🏉', 'rugby ball sport'],
      ['🎱', 'pool billiards eight ball'],
      ['🏓', 'ping pong table tennis paddle'],
      ['🏸', 'badminton shuttlecock racket'],
      ['🏒', 'hockey stick puck ice'],
      ['🥅', 'goal net sport'],
      ['⛳', 'golf flag hole course'],
      ['🏹', 'archery bow arrow aim'],
      ['🎣', 'fishing pole fish'],
      ['🤿', 'diving mask snorkel scuba'],
      ['🥊', 'boxing glove fight punch'],
      ['🥋', 'martial arts karate judo taekwondo'],
      ['🎽', 'running shirt marathon race'],
      ['🛹', 'skateboard skating skate'],
      ['⛸', 'ice skate skating rink'],
      ['🎿', 'ski skiing snow slopes'],
      ['🏂', 'snowboard snowboarding snow'],
      ['🏋️', 'weight lifting gym strength workout barbell'],
      ['🤸', 'cartwheel gymnastics tumbling'],
      ['🤺', 'fencing sword sport'],
      ['🏇', 'horse racing riding jockey'],
      ['🧘', 'yoga meditation zen mindfulness stretch calm'],
      ['🏄', 'surfing surf wave board'],
      ['🏊', 'swimming swim pool laps'],
      ['🚣', 'rowing boat row crew'],
      ['🧗', 'climbing rock climb bouldering'],
      ['🚴', 'biking cycling bicycle bike ride spin'],
      ['🚵', 'mountain biking cycling trail'],
      ['🏆', 'trophy win champion award prize'],
      ['🥇', 'gold medal first place win'],
      ['🥈', 'silver medal second place'],
      ['🥉', 'bronze medal third place'],
      ['🏅', 'medal award sports achievement'],
      ['🎫', 'ticket admission event'],
      ['🤹', 'juggling circus balance'],
      ['🎭', 'theater drama masks arts'],
      ['🎨', 'art palette paint draw creative hobby'],
      ['🎬', 'clapper movie film cinema'],
      ['🎤', 'microphone sing karaoke mic voice'],
      ['🎧', 'headphones music listen audio podcast'],
      ['🎼', 'musical score sheet music'],
      ['🎹', 'piano keyboard music keys practice'],
      ['🥁', 'drum drums percussion practice'],
      ['🎷', 'saxophone sax jazz'],
      ['🎺', 'trumpet horn brass'],
      ['🎸', 'guitar music rock practice strings'],
      ['🎻', 'violin strings orchestra practice'],
      ['🎲', 'dice game board random'],
      ['🎯', 'dart bullseye target goal aim focus'],
      ['🎳', 'bowling strike pins'],
      ['🎮', 'video game controller gaming play'],
      ['🧩', 'puzzle piece jigsaw problem'],
    ],
  },
  {
    label: 'food & drink',
    emoji: [
      ['🍏', 'green apple fruit healthy'],
      ['🍎', 'red apple fruit healthy'],
      ['🍊', 'orange tangerine citrus fruit'],
      ['🍋', 'lemon citrus sour fruit'],
      ['🍌', 'banana fruit potassium'],
      ['🍉', 'watermelon melon fruit summer'],
      ['🍇', 'grapes fruit wine'],
      ['🍓', 'strawberry berry fruit'],
      ['🫐', 'blueberries berry fruit'],
      ['🍒', 'cherries cherry fruit'],
      ['🍑', 'peach fruit'],
      ['🥭', 'mango fruit tropical'],
      ['🍍', 'pineapple fruit tropical'],
      ['🥥', 'coconut tropical'],
      ['🥝', 'kiwi fruit green'],
      ['🍅', 'tomato vegetable'],
      ['🍆', 'eggplant aubergine vegetable'],
      ['🥑', 'avocado toast healthy fat'],
      ['🥦', 'broccoli vegetable greens'],
      ['🥬', 'leafy greens lettuce spinach salad'],
      ['🥒', 'cucumber pickle vegetable'],
      ['🌶', 'chili pepper spicy hot'],
      ['🌽', 'corn maize vegetable'],
      ['🥕', 'carrot vegetable'],
      ['🥔', 'potato vegetable'],
      ['🥐', 'croissant pastry bakery breakfast'],
      ['🍞', 'bread loaf toast carbs'],
      ['🥖', 'baguette bread french'],
      ['🥨', 'pretzel snack'],
      ['🧀', 'cheese dairy'],
      ['🥚', 'egg protein breakfast'],
      ['🍳', 'cooking fried egg breakfast pan'],
      ['🥞', 'pancakes breakfast stack'],
      ['🧇', 'waffle breakfast'],
      ['🥓', 'bacon breakfast meat'],
      ['🥩', 'steak meat protein cut'],
      ['🍗', 'poultry chicken drumstick meat protein'],
      ['🌭', 'hot dog sausage'],
      ['🍔', 'hamburger burger fast food'],
      ['🍟', 'fries french chips fast food'],
      ['🍕', 'pizza slice italian'],
      ['🥪', 'sandwich lunch'],
      ['🌮', 'taco mexican'],
      ['🌯', 'burrito wrap mexican'],
      ['🥗', 'salad greens healthy veggies diet lunch'],
      ['🍝', 'spaghetti pasta noodles italian'],
      ['🍜', 'ramen noodles soup'],
      ['🍲', 'stew pot soup dinner'],
      ['🍛', 'curry rice indian'],
      ['🍣', 'sushi japanese fish'],
      ['🍱', 'bento box lunch japanese meal prep'],
      ['🥟', 'dumpling potsticker'],
      ['🍤', 'shrimp fried tempura seafood'],
      ['🍚', 'rice bowl grain'],
      ['🍡', 'dango sweet skewer'],
      ['🍧', 'shaved ice dessert'],
      ['🍨', 'ice cream dessert sweet'],
      ['🍦', 'soft serve ice cream dessert'],
      ['🥧', 'pie dessert baking'],
      ['🧁', 'cupcake dessert sweet'],
      ['🍰', 'cake slice dessert sweet'],
      ['🎂', 'birthday cake celebration party'],
      ['🍮', 'custard flan pudding dessert'],
      ['🍭', 'lollipop candy sweet'],
      ['🍬', 'candy sweet sugar'],
      ['🍫', 'chocolate bar sweet treat'],
      ['🍿', 'popcorn movie snack'],
      ['🍩', 'donut doughnut sweet'],
      ['🍪', 'cookie biscuit sweet treat'],
      ['🌰', 'chestnut nut'],
      ['🥜', 'peanuts nuts snack protein'],
      ['☕', 'coffee espresso caffeine hot drink morning'],
      ['🍵', 'tea green matcha cup hot drink'],
      ['🧃', 'juice box drink'],
      ['🥤', 'cup straw soda drink'],
      ['🍺', 'beer drink alcohol pint'],
      ['🥂', 'cheers champagne toast celebration'],
      ['🍷', 'wine glass drink alcohol'],
      ['🍸', 'cocktail martini drink alcohol'],
      ['🧉', 'mate drink herbal'],
    ],
  },
  {
    label: 'animals',
    emoji: [
      ['🐶', 'dog puppy pet'],
      ['🐱', 'cat kitten pet'],
      ['🐭', 'mouse rodent'],
      ['🐹', 'hamster pet rodent'],
      ['🐰', 'rabbit bunny'],
      ['🦊', 'fox'],
      ['🐻', 'bear'],
      ['🐼', 'panda bear'],
      ['🐨', 'koala'],
      ['🐯', 'tiger'],
      ['🦁', 'lion'],
      ['🐮', 'cow cattle'],
      ['🐷', 'pig'],
      ['🐸', 'frog'],
      ['🐵', 'monkey'],
      ['🐔', 'chicken hen'],
      ['🐧', 'penguin'],
      ['🐦', 'bird'],
      ['🐤', 'chick baby bird'],
      ['🦆', 'duck'],
      ['🦅', 'eagle bird'],
      ['🦉', 'owl night bird'],
      ['🐺', 'wolf'],
      ['🐴', 'horse'],
      ['🦄', 'unicorn magic'],
      ['🐝', 'bee honey'],
      ['🐛', 'bug caterpillar insect'],
      ['🦋', 'butterfly insect'],
      ['🐌', 'snail slow'],
      ['🐞', 'ladybug beetle insect'],
      ['🐢', 'turtle tortoise slow'],
      ['🐍', 'snake serpent'],
      ['🦎', 'lizard gecko'],
      ['🦖', 'dinosaur trex rex'],
      ['🐙', 'octopus sea'],
      ['🦀', 'crab sea'],
      ['🐠', 'tropical fish sea'],
      ['🐟', 'fish sea'],
      ['🐬', 'dolphin sea'],
      ['🐳', 'whale sea'],
      ['🦈', 'shark sea'],
      ['🦓', 'zebra stripes'],
      ['🦍', 'gorilla ape'],
      ['🐘', 'elephant'],
      ['🦒', 'giraffe tall'],
      ['🦘', 'kangaroo hop'],
      ['🐄', 'cow dairy cattle'],
      ['🐎', 'horse racing gallop'],
      ['🐖', 'pig hog'],
      ['🐑', 'sheep wool ewe'],
      ['🦙', 'llama alpaca'],
      ['🐐', 'goat'],
      ['🦌', 'deer buck'],
      ['🐕', 'dog walk pet leash'],
      ['🐈', 'cat pet feline'],
      ['🕊', 'dove peace bird'],
      ['🐇', 'rabbit bunny hop'],
      ['🦔', 'hedgehog'],
    ],
  },
  {
    label: 'nature',
    emoji: [
      ['🌵', 'cactus desert plant'],
      ['🎄', 'christmas tree holiday'],
      ['🌲', 'evergreen tree pine forest'],
      ['🌳', 'tree deciduous forest park'],
      ['🌴', 'palm tree tropical beach'],
      ['🌱', 'seedling sprout grow plant new'],
      ['🌿', 'herb plant leaves'],
      ['🍀', 'four leaf clover luck'],
      ['🍃', 'leaves wind nature'],
      ['🍂', 'fallen leaves autumn fall'],
      ['🍁', 'maple leaf autumn fall canada'],
      ['🌾', 'wheat grain harvest'],
      ['🌷', 'tulip flower spring'],
      ['🌹', 'rose flower love'],
      ['🌺', 'hibiscus flower tropical'],
      ['🌸', 'cherry blossom flower spring sakura'],
      ['🌼', 'daisy blossom flower'],
      ['🌻', 'sunflower flower'],
      ['💐', 'bouquet flowers gift'],
      ['🍄', 'mushroom fungus'],
      ['🌍', 'earth globe world planet'],
      ['🌕', 'full moon night'],
      ['🌙', 'crescent moon night sleep'],
      ['⭐', 'star favorite'],
      ['🌟', 'glowing star sparkle shine'],
      ['✨', 'sparkles shine magic clean'],
      ['⚡', 'lightning bolt energy power fast'],
      ['💥', 'boom collision explosion impact'],
      ['🔥', 'fire flame hot streak lit'],
      ['🌈', 'rainbow colors pride'],
      ['☀️', 'sun sunny bright day clear'],
      ['⛅', 'partly cloudy sun weather'],
      ['☁️', 'cloud cloudy weather'],
      ['🌧', 'rain cloud weather wet'],
      ['⛈', 'thunderstorm storm rain lightning'],
      ['❄️', 'snowflake cold winter snow'],
      ['☃️', 'snowman winter snow'],
      ['💨', 'wind dash fast air'],
      ['🌊', 'wave ocean water sea surf'],
      ['💧', 'droplet water drink hydrate'],
    ],
  },
  {
    label: 'travel & places',
    emoji: [
      ['🚗', 'car drive auto vehicle'],
      ['🚕', 'taxi cab'],
      ['🚙', 'suv car vehicle'],
      ['🚌', 'bus transit'],
      ['🏎', 'race car fast racing'],
      ['🚓', 'police car'],
      ['🚑', 'ambulance emergency medical'],
      ['🚒', 'fire truck emergency'],
      ['🛻', 'pickup truck'],
      ['🚚', 'delivery truck shipping'],
      ['🚜', 'tractor farm'],
      ['🛴', 'scooter kick'],
      ['🚲', 'bicycle bike cycling ride'],
      ['🛵', 'motor scooter moped'],
      ['🏍', 'motorcycle bike ride'],
      ['🚨', 'siren alert emergency light'],
      ['🚄', 'bullet train fast rail'],
      ['🚂', 'locomotive train steam'],
      ['🚆', 'train rail commute'],
      ['🚇', 'metro subway underground commute'],
      ['✈️', 'airplane plane flight travel'],
      ['🛫', 'departure takeoff plane travel'],
      ['🚀', 'rocket launch space fast'],
      ['🛸', 'ufo flying saucer alien'],
      ['🚁', 'helicopter chopper'],
      ['🛶', 'canoe kayak paddle'],
      ['⛵', 'sailboat sailing boat'],
      ['🚤', 'speedboat boat'],
      ['🛳', 'passenger ship cruise'],
      ['⚓', 'anchor nautical'],
      ['🗽', 'statue liberty new york'],
      ['🗼', 'tokyo tower landmark'],
      ['🏰', 'castle fortress'],
      ['🎡', 'ferris wheel fair carnival'],
      ['🎢', 'roller coaster theme park'],
      ['🎠', 'carousel merry go round'],
      ['🏖', 'beach umbrella vacation sand'],
      ['🏝', 'desert island tropical vacation'],
      ['🌋', 'volcano eruption'],
      ['⛰', 'mountain peak'],
      ['🏔', 'snowy mountain peak alps'],
      ['🏕', 'camping campsite outdoors'],
      ['⛺', 'tent camping outdoors'],
      ['🏠', 'house home'],
      ['🏡', 'house garden home'],
      ['🏢', 'office building work'],
      ['🏥', 'hospital medical doctor'],
      ['🏦', 'bank money finance'],
      ['🏨', 'hotel travel stay'],
      ['🏫', 'school class study education'],
      ['⛪', 'church chapel worship'],
      ['🕌', 'mosque worship'],
      ['🌆', 'cityscape dusk city skyline'],
      ['🌃', 'night city stars skyline'],
      ['🌉', 'bridge night'],
      ['🌅', 'sunrise morning dawn'],
    ],
  },
  {
    label: 'objects',
    emoji: [
      ['⌚', 'watch time wrist'],
      ['📱', 'phone mobile cell smartphone screen'],
      ['💻', 'laptop computer work code'],
      ['⌨️', 'keyboard typing type'],
      ['🖥', 'desktop computer monitor screen'],
      ['🖨', 'printer print'],
      ['📷', 'camera photo picture'],
      ['📸', 'camera flash photo'],
      ['🎥', 'movie camera film video'],
      ['📞', 'telephone receiver call phone'],
      ['☎️', 'telephone landline call'],
      ['📺', 'television tv watch screen'],
      ['📻', 'radio broadcast'],
      ['🎙', 'studio microphone podcast record'],
      ['⏰', 'alarm clock wake morning time'],
      ['⏳', 'hourglass time waiting timer'],
      ['🔋', 'battery charge power energy'],
      ['🔌', 'plug electric power'],
      ['💡', 'light bulb idea bright'],
      ['🔦', 'flashlight torch light'],
      ['🕯', 'candle light calm'],
      ['🗑', 'trash bin garbage waste delete'],
      ['💸', 'money wings spending cash flying'],
      ['💵', 'dollar bill money cash'],
      ['💰', 'money bag savings cash rich'],
      ['💳', 'credit card payment pay'],
      ['💎', 'gem diamond jewel valuable'],
      ['⚖️', 'scales balance justice weigh'],
      ['🧰', 'toolbox tools repair'],
      ['🔧', 'wrench tool fix repair'],
      ['🔨', 'hammer tool build'],
      ['⚙️', 'gear settings mechanics config'],
      ['🧲', 'magnet attract'],
      ['🧪', 'test tube science lab experiment'],
      ['🧬', 'dna genetics biology science'],
      ['🔬', 'microscope science lab research'],
      ['🔭', 'telescope stars astronomy'],
      ['💊', 'pill medicine vitamin supplement meds'],
      ['🩹', 'bandage plaster injury heal'],
      ['🩺', 'stethoscope doctor checkup health'],
      ['🚪', 'door entrance exit'],
      ['🛏', 'bed sleep bedroom rest'],
      ['🛋', 'couch sofa lounge living room'],
      ['🪑', 'chair seat sit'],
      ['🚽', 'toilet bathroom'],
      ['🚿', 'shower bathe wash bathroom'],
      ['🛁', 'bathtub bath soak'],
      ['🧴', 'lotion bottle soap sunscreen skincare'],
      ['🧹', 'broom sweep clean chores tidy'],
      ['🧺', 'basket laundry clothes washing chores'],
      ['🧻', 'toilet paper roll'],
      ['🧼', 'soap wash clean hygiene'],
      ['🪥', 'toothbrush teeth brush dental hygiene'],
      ['🧽', 'sponge clean dishes scrub'],
      ['🧯', 'fire extinguisher safety'],
      ['🛒', 'shopping cart groceries store errands'],
      ['🎁', 'gift present birthday wrapped'],
      ['🎈', 'balloon party celebrate'],
      ['🎀', 'ribbon bow gift'],
      ['🎉', 'party popper celebrate congrats tada'],
      ['🧸', 'teddy bear toy stuffed'],
      ['📚', 'books read study library learning'],
      ['📖', 'open book read reading study'],
      ['📝', 'memo note write journal notes'],
      ['✏️', 'pencil write draw note'],
      ['🖊', 'pen write ink'],
      ['📌', 'pushpin pin location note'],
      ['📎', 'paperclip attach'],
      ['✂️', 'scissors cut trim'],
      ['📦', 'package box shipping delivery'],
      ['📫', 'mailbox mail post letters'],
      ['🔒', 'lock locked secure private'],
      ['🔑', 'key unlock access'],
      ['🗝', 'old key vintage unlock'],
    ],
  },
  {
    label: 'symbols',
    emoji: [
      ['❤️', 'red heart love like'],
      ['🧡', 'orange heart love'],
      ['💛', 'yellow heart love friendship'],
      ['💚', 'green heart love'],
      ['💙', 'blue heart love'],
      ['💜', 'purple heart love'],
      ['🖤', 'black heart love dark'],
      ['🤍', 'white heart love pure'],
      ['💔', 'broken heart sad breakup'],
      ['💕', 'two hearts love'],
      ['💖', 'sparkling heart love shine'],
      ['💯', 'hundred percent perfect score full'],
      ['✅', 'check mark done complete yes tick'],
      ['❌', 'cross mark no wrong cancel'],
      ['⭕', 'circle red o correct'],
      ['❗', 'exclamation important warning'],
      ['❓', 'question mark help unknown'],
      ['💤', 'zzz sleep sleeping tired'],
      ['🚫', 'prohibited no forbidden ban stop'],
      ['⚠️', 'warning caution alert'],
      ['♻️', 'recycle recycling green reuse'],
      ['➕', 'plus add more'],
      ['➖', 'minus subtract less'],
      ['➗', 'divide division math'],
      ['✖️', 'multiply times math'],
      ['💲', 'dollar sign money currency'],
      ['🔔', 'bell notification alert reminder'],
      ['🎵', 'music note song'],
      ['🎶', 'music notes song melody'],
      ['🆗', 'ok button fine'],
      ['🆕', 'new button fresh'],
      ['🆓', 'free button'],
    ],
  },
]

const ALL: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emoji)

/** Emoji whose keywords contain every whitespace-separated term in the query. */
export function searchEmoji(query: string): EmojiEntry[] {
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean)
  if (terms.length === 0) return []
  return ALL.filter(([, keywords]) => terms.every((t) => keywords.includes(t)))
}
